"""empty message

Revision ID: 81d96fa7982f
Revises: d8c5877417f5
Create Date: 2020-08-25 10:09:56.038832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d96fa7982f'
down_revision = 'd8c5877417f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'gernes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('gernes', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
